package-lock.json
package.json

Bump `lumirlumir/npm-clang-format-node` from v0.0.0 to v1.0.0 :tada:

release(major): v1.0.0

---

.github/workflows/llvm-build-bump-pr.yml

An execution error occurred in the GitHub Actions runner due to permissions for `clang-format`.
The original permission was `644`, so I changed it to `755`.

fix: excution error in linux-like os for permission. 644 to 755

---

.github/workflows/llvm-build-bump-pr.yml
package-lock.json
package.json

Discard #6. It doesn't work. 
---
I used `postinstall` to solve this bug.
An execution error occurred in the GitHub Actions runner due to permissions for `clang-format`.
The original permission was `644`, so I changed it to `755`.

fix: excution error in linux-like os for permission. 644 to 755 using postinstall

---

package-lock.json
package.json

Bump `lumirlumir/npm-clang-format-node` from v1.0.0 to v1.0.1 :tada:

release(patch): v1.0.1

---

.github/workflows/llvm-build-bump-pr.yml

I fixed bugs in Windows and Linux of Github Actions runner.
In Linux, GLIBC version is not compatible.
Also in Windows, `windows-2022`(`windows-latest`) is OK. but, `windows-2019` is not compatible.
So I downgraded mac, linux, windows Image version for a better backward compatibility.

fix: update llvm-build process for backward compatibility in GitHub Actions Runner

---

package-lock.json
package.json

Bump `lumirlumir/npm-clang-format-node` from v1.0.1 to v1.0.2 :tada:

release(patch): v1.0.2

---

.github/workflows/llvm-build-bump-pr.yml

`ubuntu-latest` equals `ubuntu-22.04`. (24.09.10)

rename: ubuntu-latest to ubuntu-22.04 in llvm-build-bump-pr.yml

---

package-lock.json
package.json

Bump `lumirlumir/npm-clang-format-node` from v1.0.2 to v1.0.3 :tada:

release(patch): v1.0.3

---

package-lock.json
package.json

Bump `lumirlumir/npm-clang-format-node` from v1.0.3 to v1.1.0 :tada:

release(minor): v1.1.0

---

.github/workflows/llvm-build-bump-pr.yml

I've fixed `llvm-build-bump-pr.yml` file. 
Delete unnecessary existing dependencies. `cmake` and `python`. They are already installed in `windows-2022` runner.

fix: broken build process in `windows-2022`

---

package-lock.json
package.json

Bump `lumirlumir/npm-clang-format-node` from v1.1.1 to v1.1.2 :tada:

release(patch): v1.1.2

---

package-lock.json
package.json

Bump `lumirlumir/npm-clang-format-node` from v1.1.2 to v1.1.3 :tada:

release(patch): v1.1.3

---

.editorconfig-checker.json
.github/workflows/llvm-build-bump-pr.yml
.gitignore
package-lock.json
package.json
packages/clang-format-git-python/.gitignore
packages/clang-format-git-python/package.json
packages/clang-format-git-python/src/git-clang-format
packages/clang-format-git/.gitignore
packages/clang-format-git/package.json
packages/clang-format-node/.gitignore

New feature `git clang-format` will soon be avilable.
I need to get the latest `clang-format-git`'s binary files and `clang-format-git-python`'s script.
So, Developing `clang-format-git` and `clang-format-git-python` packages are still in progress.

refactor: create `clang-format-git` and `clang-format-git-python` package [WIP]

---

.github/workflows/test-cross-platform.yml

Delete deprecated `macos-12`. See the screenshot below.

ci(test-cross-platform): delete deprecated `macos-12`

---

package-lock.json
package.json
packages/clang-format-git-python/package.json
packages/clang-format-git-python/tsconfig.json
packages/clang-format-node/package.json
packages/clang-format-node/tsconfig.json

Now we support JSDoc type hints using typescript's `d.ts` file.
It will be located in `clang-format-.../build/index.d.ts`.

feat: support JSDoc type hints using typescript's `d.ts` file

---

package-lock.json
packages/clang-format-node/package.json
packages/clang-format-node/src/index.js
packages/clang-format-node/src/index.test.js
packages/clang-format-node/src/utils/clangFormatPath.js
packages/clang-format-node/src/utils/clangFormatPath.test.js
packages/clang-format-node/src/utils/getClangFormatPath.js
packages/clang-format-node/src/utils/getClangFormatPath.test.js

`clangFormatNodePath` equals `clangFormatPath`.
`getClangFormatNodePath` equals `getClangFormatPath`.

feat(clang-forma-node): add new API aliases `clangFormatNodePath` and `getClangFormatNodePath`

---

.github/workflows/test-cross-platform.yml
package-lock.json
packages/clang-format-git/babel.config.js
packages/clang-format-git/package.json
packages/clang-format-git/src/cli.js
packages/clang-format-git/src/cli.test.js
packages/clang-format-git/src/index.js
packages/clang-format-git/src/index.test.js
packages/clang-format-git/src/utils/getGitClangFormatPath.js
packages/clang-format-git/src/utils/getGitClangFormatPath.test.js
packages/clang-format-git/src/utils/gitClangFormatPath.js
packages/clang-format-git/src/utils/gitClangFormatPath.test.js
packages/clang-format-git/tsconfig.json

A new feature has arrived.
`clang-format-git` is now available.
See: https://github.com/lumirlumir/npm-clang-format-node/issues/60

feat(clang-format-git): create new package named `clang-format-git`

---

lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json

Bump `lumirlumir/npm-clang-format-node` from v1.1.3 to v1.2.0-canary.0 :tada:

release(preminor): v1.2.0-canary.0

---

lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json

Bump `lumirlumir/npm-clang-format-node` from v1.2.0-canary.0 to v1.2.0 :tada:

release(minor): v1.2.0

---

.github/workflows/publish.yml
package.json

ci: update `publish.yml` to fix a bug where `publish` script was overwrited

---

lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json

Bump `lumirlumir/npm-clang-format-node` from v1.2.0 to v1.2.1 :tada:

release(patch): v1.2.1

---

examples/clang-format/package.json
lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
tests/integration-api-cjs/package.json
tests/integration-api-esm/package.json
tests/integration-binaries-permission/package.json

Bump `lumirlumir/npm-clang-format-node` from v1.2.1 to v1.2.2 :tada:

release(patch): v1.2.2

---

.github/sync-client.yml
.vscode/extensions.json
package-lock.json
package.json
website/package.json

This pull request includes several important changes to the configuration files and the project structure. The most significant changes involve updates to the `.vscode` settings, the addition of a new workspace, and the creation of a `package.json` for the `website` directory.
Updates to `.vscode` settings:
* [`.github/sync-client.yml`](diffhunk://#diff-93bc202766315b6269beef308a6ad30ed3e86938ddbfa31b49e030f2263695f1L42-R42): Changed the destination of the `.vscode/extensions.json` file from `npm-extensions.json` to `web-extensions.json`.
* [`.vscode/extensions.json`](diffhunk://#diff-c16655a98a3ee89a7636a59c59a72b0e93649e3a1e947327cfc43a1336b4e912R4): Added `stylelint.vscode-stylelint` to the list of recommended extensions.
Project structure changes:
* …

chore: ready for introduction of website using `nextra`

---

.github/workflows/llvm-build-bump-pr.yml
docs/01-introduction/05-supported.md

This pull request includes updates to the macOS versions used in the GitHub Actions workflows and the corresponding documentation. The most important changes include updating the macOS version from 12 to 13 and ensuring the documentation reflects these changes.
Updates to macOS versions:
* [`.github/workflows/llvm-build-bump-pr.yml`](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0L249-R249): Changed the macOS version from 12 to 13 for x64 architecture in the matrix configuration.
Documentation updates:
* [`docs/01-introduction/05-supported.md`](diffhunk://#diff-664f5e525371f1677c342e11b06a53a625232a2dad8f12bbde8eeab27e037b09L54): Removed references to macOS 12 and updated them to macOS 13 in the supported platforms list.
* …

chore: bump macOS version references to `13` in CI workflow and documentation

---

examples/clang-format/package.json
lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
tests/integration-api-cjs/package.json
tests/integration-api-esm/package.json
tests/integration-binaries-permission/package.json
website/package.json

Bump `lumirlumir/npm-clang-format-node` from v1.2.2 to v1.2.3 :tada:

release(patch): v1.2.3

---

SECURITY.md

This pull request includes significant updates to the `SECURITY.md` file to enhance the documentation on security practices, vulnerability reporting, and binary file security. The most important changes include adding sections on binary file security, detailed instructions for reporting vulnerabilities, and security best practices.
Enhancements to security documentation:
* [`SECURITY.md`](diffhunk://#diff-f6ed156e4bf5c791680662464b94ea5d753f219ee816b385f67870e2c0d7d4c7R3-R4): Added a section on binary file security to address concerns and provide assurance about the project's handling of binary files.
* [`SECURITY.md`](diffhunk://#diff-f6ed156e4bf5c791680662464b94ea5d753f219ee816b385f67870e2c0d7d4c7L24-R56): Updated the vulnerability reporting section with detailed instructions on how to …

docs: enhance `security.md`  with vulnerability reporting guidelines

---

examples/clang-format/README.md

This pull request includes updates to the `examples/clang-format/README.md` file to improve clarity and provide more comprehensive instructions for running the example. The most important changes include renaming the example, restructuring the instructions, and expanding the list of commands.
Improvements to documentation:
* Renamed the example from `clang-format` to `examples-clang-format` for consistency.
* Restructured the instructions by adding a "Getting Started" section and separating the methods for running the example into "Run from the Root" and "Navigate to the Directory and Run" sections.
* Expanded the list of available commands to include all variations of formatted and unformatted commands for both C and C++ languages.

docs: update `README.md` of `examples-clang-format`

---

packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json

I am using [Angular clang-format](https://www.npmjs.com/package/clang-format) for formatting my C++ code used to build Node.js Native Addon. I want to support arm64 targets, and Angular clang-format only supports amd64 ones. I wanted to adopt `git-clang-format` in place of it as it bundles linux-arm64 and darwin-arm64 binaries (but not windows-arm64 which would also be highly appreciated).
I tried the following:
1. Add `clang-format-git` as dev dependency
2. Run `npm i` on windows machine
And got an error:
```
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c test -d src && npm run build || npm run chmod
npm error > clang-format-git@1.2.3 chmod
npm error > find ./src/bin ./build/bin -type f -exec chmod 755 {} + || true
npm error 'test' is not recognized as an internal or external …
```

fix: Windows support-`exit 0` instead of `true` in scripts

---

examples/clang-format/package.json
examples/git-clang-format/package.json
lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
tests/integration-api-cjs/package.json
tests/integration-api-esm/package.json
tests/integration-binaries-permission/package.json
website/package.json

Bump `lumirlumir/npm-clang-format-node` from v1.2.3 to v1.2.4 :tada:

release(patch): v1.2.4

---

package.json

This pull request includes a change to the `package.json` file to specify the required Node.js version for the project.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R4-R6): Added an `engines` field to specify that the project requires Node.js version 20.18.0 or higher.

chore: add `engines` field to `package.json`

---

examples/clang-format/package.json
examples/git-clang-format/package.json
lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
tests/integration-api-cjs/package.json
tests/integration-api-esm/package.json
tests/integration-binaries-permission/package.json
website/package.json

Bump `lumirlumir/npm-clang-format-node` from v1.2.4 to v1.2.5 :tada:

release(patch): v1.2.5

---

packages/clang-format-node/src/cli.js

This pull request includes a minor change to the `packages/clang-format-node/src/cli.js` file. The change repositions the ESLint directive `/* eslint-disable n/prefer-node-protocol */` to a different location within the file for better code organization.
* [`packages/clang-format-node/src/cli.js`](diffhunk://#diff-10e5439e75c8ce1bc7c2f61004997244cb90676b01d19b66ac9f3ba7a6b2fb67L4-R9): Moved the ESLint directive `/* eslint-disable n/prefer-node-protocol */` to a location after the file overview comment.

docs: fix incorrect comment placement

---

packages/clang-format-git-python/src/cli.js
packages/clang-format-git-python/src/utils/gitClangFormatPath.js
packages/clang-format-git/src/cli.js
packages/clang-format-git/src/utils/getGitClangFormatPath.js
packages/clang-format-git/src/utils/gitClangFormatPath.js
packages/clang-format-node/src/cli.js
packages/clang-format-node/src/utils/clangFormatPath.js
packages/clang-format-node/src/utils/getClangFormatPath.js

This pull request includes several changes across multiple files to ensure backward compatibility by not using the `node:` namespace. The changes are consistent across different files and packages.
Backward compatibility:
* [`packages/clang-format-git-python/src/cli.js`](diffhunk://#diff-93f1a01c7f4ac5a2380112cca516851320758c8184f96cddb10e1cc97012a468L7-R7): Updated eslint-disable comment to specify not using `node:` namespace for backward compatibility.
* [`packages/clang-format-git-python/src/utils/gitClangFormatPath.js`](diffhunk://#diff-0b92886b850ec05cf8174fb293fc1d7f26dfd6064e907bfc81e09da43c8e1e49L5-R5): Updated eslint-disable comment to specify not using `node:` namespace for backward compatibility.
* [`packages/clang-format-git/src/cli.js`](diffhunk://#diff-63ba214e13f2c5ab6dd124b …

docs: update eslint-disable comments for backward compatibility with `node:` namespace

---

.github/workflows/labeler.yml

This pull request includes a change to the GitHub Actions workflow for labeling pull requests. The change ensures that the labeler action runs not only when a pull request is opened but also when it is edited.
* [`.github/workflows/labeler.yml`](diffhunk://#diff-09b72f3c9a3e4f00ab00cd7000b302db25f056075d8895bd91b3654d6e7e956bL5-R13): Modified the `pull_request_target` event to include the `edited` type and added a condition to run the labeler step when the pull request is opened or its title is changed.

ci: update labeler workflow to trigger on edited pull requests

---

website/.vitepress/config.mjs
website/docs/get-started/configuration.md

This pull request includes changes to add Google Analytics to the website configuration and a minor documentation correction. The most important changes include adding the Google Analytics ID and script to the configuration file and fixing a typo in the documentation.
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71R28): Added `GOOGLE_GA_ID` constant and included Google Analytics script tags for tracking. [[1]](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71R28) [[2]](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71L70-L76)
* [`website/docs/get-started/configuration.md`](diffhunk://#diff-6a87b005e020bd2dfcf1e779a14c7ddc13bfc307a99b1b02b6c538e7f4da1b77L59-R …

refactor(website): add Google Analytics integration to `.vitepress/config.mjs`

---

website/.vitepress/config.mjs
website/docs/get-started/q-and-a.md

This pull request adds a new "Q & A" section to the documentation and updates the website configuration to include a link to this new section.
Documentation updates:
* Added a new "Q & A" section to the documentation with questions and answers about `clang-format-node`, including an explanation of the differences between `clang-format` and `git-clang-format`. (`website/docs/get-started/q-and-a.md`)
Website configuration updates:
* Updated the VitePress configuration to include a link to the new "Q & A" section in the navigation menu. (`website/.vitepress/config.mjs`)

docs: create `q-and-a.md`

---

website/docs/get-started/index.md

This pull request includes an update to the `website/docs/get-started/index.md` file to enhance the navigation within the documentation. The most important change is the addition of a link to provide context on why the project was started.
Documentation enhancement:
* [`website/docs/get-started/index.md`](diffhunk://#diff-5c932f6df78484172c717421fffc4ef01f10355cd96ebd8b86b65e02b39f99b3R3-R5): Added a "Next" section with a link to 'Why We Started This Project' to improve navigation and provide additional context for users.

docs: add navigation link to 'Why We Started This Project' in `get-started /index.md` documentation

---

website/.vitepress/config.mjs
website/docs/further-reading/surgical-formatting-with-git-clang-format.md

This pull request adds a new documentation page and updates the site configuration to include a link to this new page. The most important changes include adding a new entry to the navigation menu and creating detailed content for the new documentation page on surgical formatting with `git-clang-format`.
Documentation updates:
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71R257-R260): Added a new entry "Surgical Formatting" to the navigation menu to link to the new documentation page.
* [`website/docs/further-reading/surgical-formatting-with-git-clang-format.md`](diffhunk://#diff-4eabe91a6c51648711792a2daa82f0a8d9efcf9d01642f6940cd47868407fd84R1-R105): Created a new documentation page that explains how to use …

docs: create `surgical-formatting-with-git-clang-format.md`

---

.github/workflows/llvm-build-bump-pr.yml
website/docs/get-started/introduction.md

This pull request includes changes to update the commit message and title format in the LLVM bump workflow and a minor documentation update.
Changes to workflow:
* [`.github/workflows/llvm-build-bump-pr.yml`](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0L429-R432): Updated the commit message and title prefix from 'build(deps)' to 'chore(deps)' for consistency with other dependency updates.
Documentation update:
* [`website/docs/get-started/introduction.md`](diffhunk://#diff-aeb0fea669d0b87f99bf331106ddc13e198f254aa732266a2435acf9a98f82aaL143-R143): Added a colon at the end of the sentence to clarify the explanation of the `git diff` command output.

ci: update commit type of `llvm-build-bump-pr.yml` to `chore` from `build`

---

.github/workflows/test-cross-platform.yml

This pull request includes updates to the `.github/workflows/test-cross-platform.yml` file to enhance the testing process across different platforms. The changes mainly focus on expanding the test coverage to include various shell environments on Windows.
Enhancements to cross-platform testing:
* Added a basic test for `clang-format-node` and `clang-format-git` in the Git Bash environment.
* Included a new test for `clang-format-node` and `clang-format-git` in the Windows PowerShell environment, conditional on the runner operating system being Windows.
* Added a test for `clang-format-node` and `clang-format-git` in the Windows CMD environment, also conditional on the runner operating system being Windows.

ci: add PowerShell and CMD test to `test-cross-platform.yml`

---

packages/clang-format-git-python/src/utils/gitClangFormatPath.js
packages/clang-format-git/src/utils/getGitClangFormatPath.js
packages/clang-format-git/src/utils/gitClangFormatPath.js
packages/clang-format-node/src/utils/clangFormatPath.js
packages/clang-format-node/src/utils/getClangFormatPath.js

This pull request includes several changes to the documentation comments in various utility files across different packages. The changes primarily add references to the documentation URLs for the respective APIs.
Documentation improvements:
* [`packages/clang-format-git-python/src/utils/gitClangFormatPath.js`](diffhunk://#diff-0b92886b850ec05cf8174fb293fc1d7f26dfd6064e907bfc81e09da43c8e1e49R23): Added a reference to the documentation URL for `clang-format-git-python` in the comments for `gitClangFormatPath` and `clangFormatGitPythonPath`. [[1]](diffhunk://#diff-0b92886b850ec05cf8174fb293fc1d7f26dfd6064e907bfc81e09da43c8e1e49R23) [[2]](diffhunk://#diff-0b92886b850ec05cf8174fb293fc1d7f26dfd6064e907bfc81e09da43c8e1e49R32)
* [`packages/clang-format-git/src/utils/getGitClangFormatPath.js`](diff …

feat: add API documentation links to type files (JSDoc type hints)

---

.github/workflows/lint.yml
.github/workflows/test.yml

This pull request includes changes to the GitHub Actions workflows to add concurrency control for the `lint` and `test` jobs. The most important changes are:
GitHub Actions concurrency control:
* [`.github/workflows/lint.yml`](diffhunk://#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2R10-R13): Added concurrency control to the `lint` job to group by workflow and ref, and cancel in-progress runs for non-main branches.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R10-R13): Added concurrency control to the `test` job to group by workflow and ref, and cancel in-progress runs for non-main branches.

ci: add `concurrency` settings to `lint.yml` and `test.yml` workflows

---

examples/clang-format/package.json
examples/git-clang-format/package.json
lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
tests/integration-api-cjs/package.json
tests/integration-api-esm/package.json
tests/integration-binaries-permission/package.json
website/package.json

Bump `lumirlumir/npm-clang-format-node` from v1.2.5 to v1.3.0 :tada:

release(minor): v1.3.0

---

website/docs/get-started/introduction.md

This pull request includes a minor change to the `website/docs/get-started/introduction.md` file. The change corrects a grammatical error in a note section.
* [`website/docs/get-started/introduction.md`](diffhunk://#diff-aeb0fea669d0b87f99bf331106ddc13e198f254aa732266a2435acf9a98f82aaL20-R20): Changed "Reference" to "References" to correct the grammar in the note section.

docs: fix a typo

---

.github/sync-client.yml
scripts/vercel-ignore-command.sh
website/vercel.json

This pull request includes changes to add a new script for Vercel build ignoring, update the Vercel configuration, and modify the sync client configuration. The most important changes are:
* Added a new script `vercel-ignore-command.sh` to ignore builds for pull requests created by `dependabot[bot]` if the branch is not `main`.
* Updated `vercel.json` to include the new `ignoreCommand`, set the build and install commands, specify the framework as `vitepress`, and define the output directory.
* Updated `.github/sync-client.yml` to include the new script in the sync process.

chore: add `vercel-ignore-command.sh` script and update `vercel.json` configuration

---

.github/workflows/llvm-build-bump-pr.yml

This PR is the follow up PR of #206
Added static link for `libgcc_s_seh-1.dll`, `libwinpthread-1.dll`, and `libstdc++-6.dll`.
This updates only affect Windows binary.
---
This pull request includes a change to the `.github/workflows/llvm-build-bump-pr.yml` file to enhance the build process for `clang-format`. The most important change is the addition of static linking flags to the CMake build command.
Build process enhancement:
* [`.github/workflows/llvm-build-bump-pr.yml`](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0L372-R372): Modified the CMake build command to include `-DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++"` for static linking.

fix(ci): update `llvm-build-bump-pr.yml` LLVM build script to include static linking flags on Windows

---

SECURITY.md

This pull request includes a minor update to the `SECURITY.md` file to improve the clarity of the instructions for reviewing pull requests related to LLVM builds.
Documentation update:
* [`SECURITY.md`](diffhunk://#diff-f6ed156e4bf5c791680662464b94ea5d753f219ee816b385f67870e2c0d7d4c7L12-R12): Updated the link to the Pull Request list on GitHub to use a more specific query for filtering pull requests related to LLVM dependency bumps.

docs: correct GitHub PR list link in `SECURITY.md`

---

.github/workflows/labeler.yml

This pull request includes a change to the GitHub Actions workflow configuration to add concurrency control. The most important change is the addition of a concurrency group to the `labeler` job in the `.github/workflows/labeler.yml` file.
Improvements to GitHub Actions workflow:
* [`.github/workflows/labeler.yml`](diffhunk://#diff-09b72f3c9a3e4f00ab00cd7000b302db25f056075d8895bd91b3654d6e7e956bR7-R10): Added `concurrency` with `group` and `cancel-in-progress` to manage concurrent runs of the workflow.

ci: add `concurrency` settings to GitHub Actions `labeler.yml` workflow

---

package-lock.json
package.json
website/.vitepress/config.mjs
website/package.json

This pull request includes updates to dependencies and refactoring of the Google Analytics script in the VitePress configuration.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L50-R50): Updated `eslint-config-bananass` to version `^0.0.2`.
* [`website/package.json`](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76R11): Added `bananass-utils-vitepress` as a new dependency.
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71L7-R11): Removed the `eslint-disable` comment and imported `generateGoogleAnalyticsScript` from `bananass-utils-vitepress/head`.
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be1 …

chore: update `eslint-config-bananass` to version `0.0.2` and add `bananass-utils-vitepress` dependency

---

examples/git-clang-format/package.json
package-lock.json
package.json

This pull request includes updates to the `package.json` files to use the `shx` utility for cross-platform shell commands. The most important changes are:
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R57): Added `shx` as a dependency to the project.
Script updates:
* [`examples/git-clang-format/package.json`](diffhunk://#diff-4b5616cba814f4c7ca4ea49c77e8456efcc7931852306a3d899597507ad137b6L6-R6): Updated the `add-a-space-to-line-9-of-main-c-file` script to use `shx` for improved cross-platform compatibility.

chore(examples-git-clang-format): update script to use `shx` for cross-platform compatibility and add `shx` as a `devDependencies`

---

website/.vitepress/config.mjs

This pull request includes a minor correction in the `website/.vitepress/config.mjs` file. The change fixes a typo in a comment.
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71L92-R92): Corrected the typo from "Thme Configuration" to "Theme Configuration".

docs(website): fix a small typo

---

packages/clang-format-git-python/tsconfig.json
packages/clang-format-git/tsconfig.json
packages/clang-format-node/tsconfig.json

This pull request includes changes to the `tsconfig.json` files across multiple packages to enable JavaScript type checking. The most important changes include updating the `compilerOptions` to set `checkJs` to true.
Updates to `tsconfig.json` files:
* [`packages/clang-format-git-python/tsconfig.json`](diffhunk://#diff-da952c9797a8b0e14c1f27481ae421251f0a72d0e83c8f633293783174f619deR4): Added `"checkJs": true` to `compilerOptions`.
* [`packages/clang-format-git/tsconfig.json`](diffhunk://#diff-da952c9797a8b0e14c1f27481ae421251f0a72d0e83c8f633293783174f619deR4): Added `"checkJs": true` to `compilerOptions`.
* [`packages/clang-format-node/tsconfig.json`](diffhunk://#diff-da952c9797a8b0e14c1f27481ae421251f0a72d0e83c8f633293783174f619deR4): Added `"checkJs": true` to `compilerOptions`.

chore(*): enable `checkJs` option in TypeScript configuration for a better type checking

---

packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json

This pull request includes changes to the `package.json` files of three different packages to add a `publishConfig` section. This section ensures that the packages are published with provenance information.
Changes to `package.json` files:
* [`packages/clang-format-git-python/package.json`](diffhunk://#diff-fb0eb5dba5b2656b3fdea4322c2ed2a691973f2e9ea536ce20b36c347ab1267eR47-R49): Added a `publishConfig` section with `provenance` set to true.
* [`packages/clang-format-git/package.json`](diffhunk://#diff-d85dcfb0934f579cff896723ab5eeb9a52668d2bb322338dddd93bc1241aa4f1R46-R48): Added a `publishConfig` section with `provenance` set to true.
* [`packages/clang-format-node/package.json`](diffhunk://#diff-6e04d643c57b851ab02ad78e41531387d2cc01caf6c4cfbaa536aadd37346a30R45-R47): Added a …

chore(*): add `publishConfig` with `provenance` set to `true` in `package.json` files

---

babel.config.js
packages/clang-format-git-python/tsconfig.json
packages/clang-format-git/tsconfig.json
packages/clang-format-node/tsconfig.json

This pull request includes changes to the configuration files to adjust the exclusion patterns for test files. The most important changes involve modifying the `ignore` and `exclude` properties in various configuration files to no longer exclude `*.spec.js` files.
Configuration updates:
* [`babel.config.js`](diffhunk://#diff-09c56b2bf95de2a608a36afef3b6893146a959d6739be0a154dc9c9f02d80f24L3-R3): Updated the `ignore` property to only exclude `*.test.js` files.
* [`packages/clang-format-git-python/tsconfig.json`](diffhunk://#diff-da952c9797a8b0e14c1f27481ae421251f0a72d0e83c8f633293783174f619deL10-R10): Updated the `exclude` property to only exclude `*.test.js` files.
* [`packages/clang-format-git/tsconfig.json`](diffhunk://#diff-da952c9797a8b0e14c1f27481ae421251f0a72d0e83c8f633293783174f619d …

chore(*): remove `.spec.js` files from exclusion and ignore lists

---

package.json

This pull request includes a small but important change to the `package.json` file. The change updates the `publish-package` script to use a different pre-distribution tag.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L15-R15): Changed the `publish-package` script to use `next` instead of `canary` as the pre-distribution tag.

chore(*): update `publish-package` script to use `next` pre-dist tag

---

examples/clang-format/package.json
examples/git-clang-format/package.json
lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
tests/integration-api-cjs/package.json
tests/integration-api-esm/package.json
tests/integration-binaries-permission/package.json
website/package.json

New release of `lumirlumir/npm-clang-format-node` has arrived! :tada:
This PR bumps the package versions from `v1.3.1` to `v1.3.2` (`patch`).
See [Actions](https://github.com/lumirlumir/npm-clang-format-node/actions/runs/13613429578) for more details.
| Info        | Value                      |
| ----------- | -------------------------- |
| Repository  | `lumirlumir/npm-clang-format-node` |
| SEMVER      | `patch`     |
| Pre ID      | `canary`      |
| Short SHA   | 006d2eb       |
| Old Version | `v1.3.1`  |
| New Version | `v1.3.2`  |
* chore(examples-git-clang-format): update script to use `shx` for cross-platform compatibility and add `shx` as a `devDependencies` by @lumirlumir in https://github.com/lumirlumir/npm-clang-format-node/pull/217
* chore(*): enable `checkJs` option in …

chore(release): bump package versions from `v1.3.1` to `v1.3.2` (`patch`)

---

.github/workflows/publish.yml

This pull request includes a small change to the `.github/workflows/publish.yml` file. The change adds permissions for `id-token` to the workflow configuration.

ci(*): add `id-token` write permission to `publish.yml`

---

.github/workflows/test-cross-platform.yml

This pull request includes a small but important change to the GitHub Actions workflow configuration file `.github/workflows/test-cross-platform.yml`. The change grants read permissions to the contents of the repository.
* [`.github/workflows/test-cross-platform.yml`](diffhunk://#diff-290907d9a4bcf13181105b134bd1645da5a3ef27c54f148ad5823e6b77e88426R14-R16): Added `permissions` section to grant read access to repository contents.

ci(*): add read permissions to `test-cross-platform.yml`

---

.github/workflows/llvm-build-bump-pr.yml

This pull request includes updates to the GitHub Actions workflow for the LLVM build process. The main changes involve adding permissions and modifying job strategies to improve the workflow's robustness and security.
Workflow improvements:
* [`.github/workflows/llvm-build-bump-pr.yml`](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0R15-R17): Added `contents: read` permission to the workflow to enhance security.
* [`.github/workflows/llvm-build-bump-pr.yml`](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0R144): Set `fail-fast: false` in the strategy for the `stage2-build-linux-qemu` job to prevent the entire job matrix from failing on a single failure.
* [`.github/workflows/llvm-build-bump-pr.yml`](diffhunk://#diff-d608eb7 …

ci(*): update `llvm-build-bump-pr.yml` to add `permissions` and disable `fail-fast` strategy

---

.github/workflows/llvm-build-bump-pr.yml

This pull request includes several updates to the `.github/workflows/llvm-build-bump-pr.yml` file to enhance the build process and improve artifact handling. The most important changes include adding IDs to the artifact upload steps, incorporating build attestation steps, and updating permissions.
Enhancements to the build process:
* Added IDs to the artifact upload steps for better reference and traceability. [[1]](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0R109-R133) [[2]](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0R149-R159) [[3]](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0R249-R277) [[4]](diffhunk://#diff-d608eb75b383338d789a8908995e47499214a7cc55a847771ad73800464b18b0R332- …

ci(*): update `llvm-build-bump-pr.yml` to enhance permissions and add build provenance attestations

---

package-lock.json
website/.vitepress/config.mjs
website/package.json

This pull request includes the integration of the Codecov Vite plugin into the VitePress configuration for the website. The most important changes are as follows:
Integration of Codecov Vite plugin:
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71R15): Added import statement for `codecovVitePlugin` from `@codecov/vite-plugin`.
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71L336-R346): Updated the Vite configuration to include `codecovVitePlugin` with specific options such as enabling bundle analysis, setting the bundle name, providing the upload token from environment variables, and specifying the git service as GitHub.
* …

chore(website): add Codecov Vite plugin and update related configs for bundle analyzing

---

package-lock.json
website/.vitepress/config.mjs
website/package.json

This pull request includes changes to the `website/.vitepress/config.mjs` and `website/package.json` files to improve the configuration and dependency management for the project. The most important changes include the addition of the `is-interactive` package and adjustments to the Codecov plugin configuration to work better in CI environments.
Dependency management and configuration improvements:
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71R16): Added import for the `is-interactive` package to the configuration file.
* [`website/.vitepress/config.mjs`](diffhunk://#diff-bd4ac01d4c35583e9c20414103304b0628a6be199987bd1084fdef61cd43cc71L341-R342): Modified the `enableBundleAnalysis` option for the Codecov plugin to use …

chore(website): conditionally enable bundle analysis in Codecov Vite plugin

---

README.md

This pull request includes a small change to the `README.md` file. The change removes the Code Climate maintainability badge.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L12): Removed the Code Climate maintainability badge.

docs(*): delete maintainability badge from `README.md`

---

examples/clang-format/package.json
examples/git-clang-format/package.json
lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
tests/integration-api-cjs/package.json
tests/integration-api-esm/package.json
tests/integration-binaries-permission/package.json
website/package.json

New release of `lumirlumir/npm-clang-format-node` has arrived! :tada:
This PR bumps the package versions from `v1.3.2` to `v1.3.3` (`patch`).
See [Actions](https://github.com/lumirlumir/npm-clang-format-node/actions/runs/14215733817) for more details.
| Info        | Value                      |
| ----------- | -------------------------- |
| Repository  | `lumirlumir/npm-clang-format-node` |
| SEMVER      | `patch`     |
| Pre ID      | `canary`      |
| Short SHA   | ed550b4       |
| Old Version | `v1.3.2`  |
| New Version | `v1.3.3`  |
* chore(sync-server): update `lint-staged.config.js` by @lumirlumir in https://github.com/lumirlumir/npm-clang-format-node/pull/259
* chore(sync-server): update `.editorconfig` `max_line_length` to `100000` by @lumirlumir in …

chore(release): bump package versions from `v1.3.2` to `v1.3.3` (`patch`) 

---

.github/dependabot.yml
package-lock.json
website/.vitepress/config.js
website/.vitepress/theme/index.js
website/package.json

This pull request removes the dependency on `bananass-utils-vitepress` across the project and replaces its functionality with direct implementations where needed. Additionally, it updates the Google Analytics integration in the VitePress configuration.
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L16): Removed `bananass-utils-vitepress` from the `bananass` update group patterns.
* [`website/.vitepress/config.js`](diffhunk://#diff-44d6965b3c2f9329fe9aacf68bd5c4f638b1ff0d4b1b08649486193c906d68d1L3-L11): Removed the import of `generateGoogleAnalyticsScript` from `bananass-utils-vitepress/head`.
* [`website/package.json`](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76L13): Removed …

chore(*): remove `bananass-utils-vitepress` dependency

---

.github/FUNDING.yml
.github/sync-client.yml

This pull request removes the funding configuration for the `lumirlumir` project and updates the synchronization configuration to stop syncing the removed funding file. These changes are focused on cleaning up unused or outdated configuration files.
Configuration cleanup:
* [`.github/FUNDING.yml`](diffhunk://#diff-07985fdcade0e64d11482724879a644f07879ba61b8fb6c6119e1b1902b72ae4L1-L2): Removed the funding configuration for the `lumirlumir` project, including references to GitHub and Open Collective.
* [`.github/sync-client.yml`](diffhunk://#diff-93bc202766315b6269beef308a6ad30ed3e86938ddbfa31b49e030f2263695f1L29-L30): Updated the synchronization configuration by removing the entry for syncing the `FUNDING.yml` file.

chore(*): move `FUNDING.yml` files to `.github` repository

---

examples/git-clang-format/package.json
package-lock.json
package.json

This pull request updates the `examples/git-clang-format/package.json` file to replace the use of `shx` with a native Node.js solution and removes the `shx` dependency from the project's `package.json`.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L64): Removed the `shx` dependency, as it is no longer needed after switching to a native Node.js approach.
Script updates:
* [`examples/git-clang-format/package.json`](diffhunk://#diff-4b5616cba814f4c7ca4ea49c77e8456efcc7931852306a3d899597507ad137b6L6-R6): Replaced the `shx` command in the `add-a-space-to-line-9-of-main-c-file` script with a Node.js `fs.copyFileSync` operation for copying files.

chore(*): replace `shx` with native Node.js file operations in scripts

---

.github/workflows/test-cross-platform.yml
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json

This pull request introduces changes to streamline build processes and simplify post-installation scripts across multiple packages. The most notable updates include adding a build step to the cross-platform workflow and removing conditional checks in post-installation scripts for various packages.
* [`.github/workflows/test-cross-platform.yml`](diffhunk://#diff-290907d9a4bcf13181105b134bd1645da5a3ef27c54f148ad5823e6b77e88426R44-R46): Added a `Build` step to the workflow to ensure packages are built before testing. (`[.github/workflows/test-cross-platform.ymlR44-R46](diffhunk://#diff-290907d9a4bcf13181105b134bd1645da5a3ef27c54f148ad5823e6b77e88426R44-R46)`)
* [`packages/clang-format-git-python/package.json`](diffhunk://#diff-fb0eb5dba5b2656b3fdea4322c2ed2a691973f2e9ea536ce20b36c347ab1267eL5 …

fix(*): update `postinstall` script to remove unnecessary build check

---

examples/clang-format/package.json
examples/git-clang-format/package.json
lerna.json
package-lock.json
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
tests/integration-api-cjs/package.json
tests/integration-api-esm/package.json
tests/integration-binaries-permission/package.json
website/package.json

New release of `lumirlumir/npm-clang-format-node` has arrived! :tada:
This PR bumps the package versions from `v1.3.3` to `v1.3.4` (`patch`).
See [Actions](https://github.com/lumirlumir/npm-clang-format-node/actions/runs/16236437387) for more details.
| Info        | Value                      |
| ----------- | -------------------------- |
| Repository  | `lumirlumir/npm-clang-format-node` |
| SEMVER      | `patch`     |
| Pre ID      | `canary`      |
| Short SHA   | 5862509       |
| Old Version | `v1.3.3`  |
| New Version | `v1.3.4`  |
* fix(*): update `postinstall` script to remove unnecessary build check by @lumirlumir in https://github.com/lumirlumir/npm-clang-format-node/pull/398
* chore(*): update configuration files to use `.cjs` or `.mjs` extensions by @lumirlumir in …

chore(release): bump package versions from `v1.3.3` to `v1.3.4` (`patch`)

---

.github/sync-client.yml
.github/workflows/test-cross-platform.yml
packages/clang-format-git-python/package.json
packages/clang-format-git/package.json
packages/clang-format-node/package.json
scripts/cp.mjs
website/docs/further-reading/build-process.md

This pull request introduces updates to streamline file copying processes across multiple packages, refactor scripts for consistency, and improve documentation. The most significant changes involve the addition of a reusable file copy script (`cp.mjs`), updates to package build commands to use this script, and the replacement of `apt` commands with `apt-get` for better compatibility.
* Added a new script `scripts/cp.mjs` to facilitate file copying with support for recursive and forced operations. This script is now reusable across packages.
* Updated `build` scripts in `packages/clang-format-git-python/package.json`, `packages/clang-format-git/package.json`, and `packages/clang-format-node/package.json` to replace `shx cp` commands with `node ../../scripts/cp.mjs`, enhancing consistency …

build(*): add `cp.mjs` script for file copying and update build scripts

---

package-lock.json
website/package.json

This pull request updates the `vitepress` dependency in the `website/package.json` file to a newer version. The version has been changed from `^1.6.3` to `^2.0.0-alpha.9`.

chore(deps-dev): bump `vitepress` to `alpha` version

---

package-lock.json
package.json
website/docs/get-started/introduction.md

This pull request includes minor dependency updates in the `package.json` file. The changes update the versions of `eslint-plugin-mark` and `textlint-rule-allowed-uris` to their latest releases, ensuring better compatibility and access to recent bug fixes and features. 
* Upgraded `eslint-plugin-mark` from version `0.1.0-canary.1` to `0.1.0-canary.7` for improved linting capabilities.
* Updated `textlint-rule-allowed-uris` from version `2.0.0` to `2.0.1` for enhanced text linting support.

chore(deps-dev): bump `textlint-rule-allowed-uris` and `eslint-plugin-mark`

---

package-lock.json
package.json
website/package.json

This pull request updates development dependencies in the project to their latest minor versions. The changes help keep the tooling up-to-date and may include bug fixes and improvements from upstream.
Dependency updates:
* Upgraded `husky` in the root `package.json` from version `9.1.5` to `9.1.7` for improved git hook management.
* Upgraded `vitepress` in `website/package.json` from version `2.0.0-alpha.11` to `2.0.0-alpha.12` for the documentation site.

chore(deps-dev): bump dependencies
